title: "keygen"

minima:
  social_links:
    twitter: jseeio
    facebook: jseeio
    github: jseeio/keygen

remote_theme: "jseeio/minima"

logo_footer:
  src: https://jsee.io/design/jsee_logo.svg
  href: https://jsee.io/
  width: 50

jsee_version: "0.2"
jsee_schema: "schema.json"
jsee_runtime: true
