title: "Generate public and private RSA keys online"

author:
  name: "zemlyansky"
  email: "anton.zemlyansky@gmail.com"

minima:
  social_links:
    twitter: zemlyansky
    github:  zemlyansky

remote_theme: "jseeio/minima"

port_version: "0.2.0"
port_schema: "schema.json"
port_runtime: true
