title: "keygen"

minima:
  social_links:
    twitter: jseeio
    github:  jseeio

remote_theme: "jseeio/minima"

logo_footer:
  src: https://jsee.io/assets/jsee_logo.svg
  href: https://jsee.io/
  width: 50

jsee_version: "0.2"
jsee_schema: "schema.json"
jsee_runtime: true
